# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_search_site_master',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('serch_site', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30b5\u30a4\u30c8')),
                ('request_url', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30ea\u30af\u30a8\u30b9\u30c8URL')),
            ],
        ),
        migrations.CreateModel(
            name='T_search_result',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30ef\u30fc\u30c9')),
                ('serch_site', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30b5\u30a4\u30c8')),
                ('serch_date', models.DateTimeField(verbose_name='\u691c\u7d22\u5b9f\u884c\u65e5')),
                ('serch_cnt', models.IntegerField(blank=True, default=0, verbose_name='\u691c\u7d22\u7d50\u679c\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='T_search_result_detail',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30ef\u30fc\u30c9')),
                ('serch_site', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30b5\u30a4\u30c8')),
                ('write_user_name', models.CharField(blank=True, max_length=255, verbose_name='\u7b46\u8005')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u30bf\u30a4\u30c8\u30eb')),
                ('body', models.TextField(blank=True, verbose_name='\u672c\u6587')),
                ('write_date', models.DateTimeField(verbose_name='\u4f5c\u6210\u65e5')),
                ('fav_cnt', models.IntegerField(blank=True, default=0, verbose_name='\u304a\u6c17\u306b\u5165\u308a\u6570')),
                ('buzz_cnt', models.IntegerField(blank=True, default=0, verbose_name='\u62e1\u6563\u6570')),
                ('comment_cnt', models.IntegerField(blank=True, default=0, verbose_name='\u30b3\u30e1\u30f3\u30c8\u6570')),
                ('t_search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='T_search_result_details', to='cms.T_search_result', verbose_name='\u691c\u7d22\u7d50\u679c\u30b5\u30de\u30ea')),
            ],
        ),
    ]
