# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serch_site', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30b5\u30a4\u30c8')),
                ('request_url', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30ea\u30af\u30a8\u30b9\u30c8URL')),
            ],
        ),
        migrations.AlterField(
            model_name='m_search_site_master',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
