# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20160220_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_search_site_master',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
