# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20160220_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30ef\u30fc\u30c9')),
                ('serch_site', models.CharField(blank=True, max_length=255, verbose_name='\u691c\u7d22\u30b5\u30a4\u30c8')),
                ('write_user_name', models.CharField(blank=True, max_length=255, verbose_name='\u7b46\u8005')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u30bf\u30a4\u30c8\u30eb')),
                ('body', models.TextField(blank=True, verbose_name='\u672c\u6587')),
                ('write_date', models.DateTimeField(verbose_name='\u4f5c\u6210\u65e5')),
                ('fav_cnt', models.IntegerField(blank=True, default=0, verbose_name='\u304a\u6c17\u306b\u5165\u308a\u6570')),
                ('buzz_cnt', models.IntegerField(blank=True, default=0, verbose_name='\u62e1\u6563\u6570')),
                ('comment_cnt', models.IntegerField(blank=True, default=0, verbose_name='\u30b3\u30e1\u30f3\u30c8\u6570')),
            ],
        ),
        migrations.RenameModel(
            old_name='T_search_result',
            new_name='Result',
        ),
        migrations.DeleteModel(
            name='M_search_site_master',
        ),
        migrations.RemoveField(
            model_name='t_search_result_detail',
            name='t_search_result',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='url',
            new_name='request_url',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site',
            new_name='serch_site',
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='T_search_result_detail',
        ),
        migrations.AddField(
            model_name='detail',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cms.Result', verbose_name='\u691c\u7d22\u7d50\u679c\u30b5\u30de\u30ea'),
        ),
    ]
